version: '3.8'

services:
  app:
    build:
      dockerfile: dockers/app/Dockerfile.local
      context: .
      args:
        NODE_IMAGE: ${NODE_IMAGE}
        APP_PORT: ${APP_PORT}
    container_name: ${APP_NAME}-app
    env_file:
      - .env
    ports:
      - 3000:${APP_PORT}
    command: yarn start:dev
    volumes:
      - ./:/home/app
      - ./node_modules:/home/app/node_modules
    networks:
      - backend
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: ${APP_NAME}-db
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - 5432:${DB_PORT}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - backend
  
networks:
  backend:
    name: ${APP_NAME}-local-network

volumes:
  postgres-data: